section module
GenesisKernel/genesis-front pull request #56
Opened 2018-05-30 06:44 UTC by av-alex

2018-05-31 05:06 UTC, Saurer requested changes
Rename module to "sections"

2018-05-31 05:06 UTC, Saurer commented on src/app/modules/section/reducer.ts
> +import * as contentActions from 'modules/content/actions';
Module is referencing actions from another module. It must be self-aware

2018-05-31 06:23 UTC, av-alex commented on src/app/modules/section/reducer.ts
> +import * as contentActions from 'modules/content/actions';
The same action and reducer are used in "content" module. 
https://github.com/GenesisKernel/genesis-front/blob/AF-10/src/app/modules/content/reducers/ecosystemInitDoneHandler.ts

2018-06-07 08:17 UTC, Saurer requested changes

2018-06-07 08:17 UTC, Saurer commented on src/app/modules/sections/epics/ecosystemInitEpic.ts
> +const ecosystemInitEpic: Epic = (action$, store, { api }) => action$.ofAction(ecosystemInitSections.started)
Rename to initSectionsEpic

2018-06-07 08:17 UTC, Saurer commented on src/app/containers/Main/Navigation/index.tsx
> +import { menuPop, menuPush, ecosystemInit as ecosystemInitSection } from 'modules/sections/actions';
Instead of adding a name alias consider renaming modules/sections/actions/ecosystemInit to sectionsInit to represent an actual workflow of the action

2018-06-08 14:01 UTC, Saurer approved these changes

2018-06-08 21:01 UTC, merged