Af 141
GenesisKernel/genesis-front pull request #58
Opened 2018-06-04 20:32 UTC by av-alex

2018-06-07 08:14 UTC, Saurer requested changes

2018-06-07 08:14 UTC, Saurer commented on src/app/components/Modal/Auth/AuthChangePasswordModal.tsx
> +                            key={'password_new_repeat' + this.state.newPassword}
Key is not required here

2018-06-07 08:14 UTC, Saurer commented on src/app/components/Modal/Auth/AuthChangePasswordModal.tsx
> +                            key="password_new"
Key is not required here

2018-06-07 08:14 UTC, Saurer commented on src/app/components/Modal/Auth/AuthChangePasswordModal.tsx
> +                            key={'password_new_repeat' + this.state.newPassword}
User password can be stolen by an extension that have access to the page DOM

2018-06-07 08:14 UTC, Saurer commented on src/app/modules/auth/epics/openChangePasswordEpic.ts
> +const openChangePasswordEpic: Epic = (action$, store) => action$.ofAction(openChangePassword)
Must be renamed to changePasswordEpic since it not only opens the password change dialog, but also saves new password. It also applies to the action itself

2018-06-07 08:14 UTC, Saurer commented on src/app/modules/storage/epics/saveEncKeyEpic.ts
> +            saveEncKey(action.payload.result)
Can be used with saveWallet

2018-06-07 08:14 UTC, Saurer commented on src/app/modules/storage/reducers/saveEncKeyHandler.ts
> +            ...state.wallets.filter(l => l.id !== payload.id),
Iterating over the wallets array twice can be replaced by single wallets.map returning either changed or unchanged value

2018-06-07 21:01 UTC, av-alex commented on src/app/components/Modal/Auth/AuthChangePasswordModal.tsx
> +                            key={'password_new_repeat' + this.state.newPassword}
Key (or other unique property) is required to update component because its validation rule depends on other password input (repeatPassword must be equal to password).

2018-06-07 21:30 UTC, av-alex commented on src/app/modules/auth/epics/openChangePasswordEpic.ts
> +const openChangePasswordEpic: Epic = (action$, store) => action$.ofAction(openChangePassword)
There is already a src/app/modules/auth/epics/openChangePasswordEpic.ts epic which does the work. 
openChangePasswordEpic only opens the dialog.

2018-06-07 21:31 UTC, av-alex commented on src/app/components/Modal/Auth/AuthChangePasswordModal.tsx
> +                            key="password_new"
ok, fixed

2018-06-07 21:37 UTC, av-alex commented on src/app/modules/storage/epics/saveEncKeyEpic.ts
> +            saveEncKey(action.payload.result)
ok

2018-06-07 21:37 UTC, av-alex commented on src/app/modules/storage/reducers/saveEncKeyHandler.ts
> +            ...state.wallets.filter(l => l.id !== payload.id),
ok

2018-06-08 13:48 UTC, Saurer approved these changes

2018-06-09 10:34 UTC, merged