translation fixes
GenesisKernel/genesis-front pull request #78
Opened 2018-09-26 16:22 UTC by atomzakk

2018-09-26 23:44 UTC, Saurer requested changes
Greetings, atomzakk.
I've reviewed your proposed changes and submitted a feedback. Unfortunately, there are some issues that you will need to resolve before this pull request will be allowed to merge. Please check the recommendations regarding those issues and try to modify your code accordingly.

Thank you for your contribution.

2018-09-26 23:44 UTC, Saurer commented on src/app/lib/en-US.json
> +    "auth.role.disclaimer": "Select role that you want to use to login. Data representation will change according to selected role. You can switch between the roles any time",
Missing article. Consider writing as "to the selected role"
Also there: redundant article and missing "at": "you can switch between roles **at** any time"

2018-09-26 23:44 UTC, Saurer commented on src/app/lib/en-US.json
> +    "auth.havekey.desc": "If you are already familiar with Genesis and have a backup of your private key, select this option to guide you through the process of restoring your wallet data",
"Choose" is more preferred since the actual process of making a decision is represented by a form with multiple buttons rather than a radio group. That is, the user immediately chooses an option without confirmation

2018-09-26 23:44 UTC, Saurer commented on src/app/lib/en-US.json
> +    "auth.nokey.desc": "If you are new to the system or just want to create a new wallet, select this option to generate new private key and protect it with your password",
"Choose" is more preferred instead of "select". Also, missing an "a" article: "generate **a** new private key"

2018-09-26 23:44 UTC, Saurer commented on src/app/lib/en-US.json
> +    "auth.welcome.guide": "Before proceed, you will be guided through the wallet creation process. This will not take too much time. After completing this process you will be able to use all features
Both versions are acceptable, but writing "Before proceed" is grammatically incorrect. Though it can be replaced to "Before continuing", I don't see problems with the initial variant

2018-09-27 00:05 UTC, atomzakk commented
Great English! Recommendations accepted.
Thank you!

2018-09-27 01:22 UTC, Saurer approved these changes
All issues were resolved therefore I am glad to give a green light.
Thank you and congratulations with your first contribution to genesis-front.

2018-09-27 01:23 UTC, merged